In [1]:
import numpy as np

In [2]:
# CREATE 0-D ARRAY 
arrzero = np.array(80)  # only one element is required to make 0-D
print(arrzero)

80


In [3]:
# CREATE 1-D ARRAY 
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
# CREATE 2-D ARRAY  
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])       
print(arr2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [5]:
# CHECK THE DIMENSION OF THE ABOVE ARRAY  
print(arr.ndim)         # ndim is a method in ndarray to check the dimension 
print(arrzero.ndim)
print(arr2.ndim)

1
0
2


In [6]:
# NUMBER OF ELEMENTS USED IN ARRAY  
print(arrzero.size)
print(arr.size)
print(arr2.size)

1
5
10


In [7]:
# TOTAL MEMORY TAKEN BY AN ARRAY  
print(arrzero.nbytes)             # nbytes is a method, it tells total bytes consumed by the array as 1 element = 4 byte 
print(arr.nbytes)
print(arr2.nbytes)

4
20
40


In [8]:
# SINGLE ELEMENT SIZE OF ARRAY 
print(arrzero.itemsize)          
print(arr.itemsize)
print(arr2.itemsize)

4
4
4


In [9]:
# CHECK THE DATA TYPE OF THE ARRAY 
print(arrzero.dtype)
print(arr.dtype)
print(arr2.dtype)

int32
int32
int32


In [10]:
# TAKING OUT SPECIFIC ELEMENT OF THE ARRAY 
print(arr2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [11]:
arr2[0,3]       # 0 is the row and 3 is the index number 

4

In [12]:
# SPECIFIC ROW OF THE ARRAY 
print(arr2[1,:])     # ":" print the starting to end elements of the mention row

[6 7 8 9 0]


In [ ]:
#SLICING

In [13]:
# CREATING AN ARRAY  
arr3 = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr3)

[1 2 3 4 5 6 7 8 9 0]


In [14]:
# PERFORMING SLICING 
# [start_index : ending_index]
# [inclusive : exclusive]
# slicing work with the given start no. and at the end, slicing work as -1 of the given end no.
print(arr3[0:4]) 

[1 2 3 4]


In [15]:
print(arr3[2:])

[3 4 5 6 7 8 9 0]


In [16]:
print(arr3[:7])

[1 2 3 4 5 6 7]


In [17]:
print(arr2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [18]:
# [row_num , start_index : end_index]
print(arr2[1,1:3])

[7 8]


In [19]:
# COPYING OF AN ARRAY
arr4 = arr2.copy()       #copy()_function 
print(arr4)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [20]:
# PRINTING ZERO MATRIX 
# (row_num , column_num)
np.zeros((3,3))  

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# 1 MATRIX 
# (no. of matrix , row_num , column_num)
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
# OTHER MATRIX 
# ((row_num , column_num), num to be print in matrix)
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [23]:
# DECIMAL NUMBER ARRAY 
# importing random 

from numpy import random

In [24]:
np.random.rand(3,3)

array([[0.808533  , 0.55556484, 0.34874859],
       [0.61651861, 0.43289215, 0.37058168],
       [0.53948262, 0.65564748, 0.61634296]])

In [25]:
# IDENTITY MATRIX 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# MATHEMATICAL OPERATION ON MATRIX 

arrm = np.array([10,20,30,40])
print(arrm)

[10 20 30 40]


In [27]:
# addition operation 
arrm = arrm+5
print(arrm)

[15 25 35 45]


In [28]:
# substraction operation 
arrm = arrm-4
print(arrm)

[11 21 31 41]


In [29]:
# multiplication operation 
arrm = arrm*3
print(arrm)

[ 33  63  93 123]


In [30]:
# division operation 
arrm = arrm/4
print(arrm)

[ 8.25 15.75 23.25 30.75]


In [31]:
# addition of array 
a1 = np.array([1,2,3])
a2 = np.array([10,20,30])
print(a1 + a2)

[11 22 33]


In [32]:
# COS function 
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [33]:
# min and max value in array 
print(arr2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [34]:
np.min(arr2) 

0

In [ ]:
np.max(arr2)

In [35]:
# sum of elements in array 
np.sum(arr2)

45

In [36]:
# iteration in 1-D
for x in arr:
    print(x)

1
2
3
4
5


In [37]:
# ineration in 2-D
for a in arr2:
    print(a)

[1 2 3 4 5]
[6 7 8 9 0]


In [38]:
for z in arr2:
    for y in z:
        print(y)

1
2
3
4
5
6
7
8
9
0
